import type { Metadata } from "next";
import "./globals.css";
import { Bodoni_Moda, Didact_Gothic } from "next/font/google"


const bodoni = Bodoni_Moda({
    subsets: ["latin"],
    variable: "--font-bodoni",
})

const didact = Didact_Gothic({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-didact",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${bodoni.variable} ${didact.variable}`}>
        <body className="flex justify-center bg-black min-h-dvh">
        <div className="relative w-[390px] min-h-dvh bg-bg overflow-hidden">
            {children}
        </div>
        </body>
        </html>
    )
}
